services:
  webhook:
    ports:
      - "80:8091"
    image: "builds/webhook:latest"
    container_name: "webhooks"
    restart: always
    networks:
        - web
    labels:
      - traefik.http.routers.builds-2.rule=(Host(`www.plutimus.com`) || Host (`plutimus.com`)) && Path(`/builds-2`)
      - traefik.http.routers.builds-2.tls=true
      - traefik.http.routers.builds-2.tls.certresolver=le
      - traefik.http.middlewares.builds-2.compress=true
      - traefik.http.routers.builds-2.middlewares=builds-2@docker
