services:
  webhook:
    image: "paolino/buildkite-notification:latest"
    container_name: "buildkite-notification"
    restart: always
    networks:
        - web
    ports:
      - "8081:8081"
    labels:


      - "traefik.enable=true"
      - "traefik.http.services.buildkite-notification.loadbalancer.server.port=8081"
      - "traefik.http.routers.buildkite-notification.rule=Host(`plutimus.com`) && PathPrefix(`/buildkite-notification/`)"
      - "traefik.http.middlewares.buildkite-notificationpre.stripprefix.prefixes=/buildkite-notification"
      - "traefik.http.routers.buildkite-notification.tls=true"
      - "traefik.http.routers.buildkite-notification.tls.certresolver=le"
      - "traefik.http.routers.buildkite-notification.middlewares=buildkite-notificationpre"
networks:
    web:
        external: true
