name: Build
on:
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  merge_group:
  push:
    branches:
      - main
  schedule:
    # Run once per day (at UTC 18:00) to maintain cache:
    - cron: 0 18 * * *
jobs:
  build:
    name: build-ghc-9.4.5
    runs-on: ubuntu-latest
    env:
      cabal-build-dir: b

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Environment
        uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: 9.4.5
          cabal-version: 3.8.1.0

      - name: Configure
        run: >
          cabal configure
          --builddir=${{ env.cabal-build-dir }}
          --enable-tests
          --enable-benchmarks
          --enable-documentation
          --test-show-details=direct
          --write-ghc-environment-files=always

      - name: Freeze
        run: >
          cabal freeze
          --builddir=${{ env.cabal-build-dir }}

      - name: Cache
        uses: actions/cache@v3
        env:
          hash: ${{ hashFiles('cabal.project.freeze') }}
        with:
          key: build-ghc-9.4.5-${{ env.hash }}
          restore-keys: |
            build-ghc-9.4.5-
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            ${{ env.cabal-build-dir }}

      - name: Dependencies
        run: >
          cabal build all
          --builddir=${{ env.cabal-build-dir }}
          --only-dependencies

      - name: Build
        run: >
          cabal build all
          --builddir=${{ env.cabal-build-dir }}
          --enable-tests
          --enable-benchmarks
          --ghc-options=-Werror
          --ghc-options=-Wall

      - name: Test
        run: >
          cabal test all
          --builddir=${{ env.cabal-build-dir }}

      - name: Benchmark
        run: >
          cabal bench all
          --builddir=${{ env.cabal-build-dir }}
          || true

      - name: Documentation (Generation)
        run: >
          cabal haddock all
          --builddir=${{ env.cabal-build-dir }}
          --enable-documentation
          --haddock-hyperlink-source
          --haddock-html-location
          'https://hackage.haskell.org/package/$pkg-$version/docs'

      - name: Documentation (Staging)
        if: |
            github.ref == 'refs/heads/main'

        run: >
          mv ${{ env.cabal-build-dir }}/build/*/*/*/doc/html/* gh-pages

          touch gh-pages/.nojekyll

      - name: Documentation (Deployment)
        if: |
            github.ref == 'refs/heads/main'

        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
      - name: install

        run: >
          cabal -v0 install
          --enable-executable-static
          --installdir=build
          --overwrite-policy=always
          --install-method=copy

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: paolino/buildkite-notification:latest

# github.ref == 'refs/heads/main' &&